### ISSUE TITLE
Needs "pecl install ast" for phan to work

### ISSUE THREAD

**Issue by addshore** [addshore/mediawiki-docker-dev#106]
Also needs adding to the php.ini

Might be easier to start using the WMF php images..

**Comment by jakobw** [comment]
Running `vendor/bin/phan --allow-polyfill-parser .` works for me. It's slow and downloads half the internet along the way, but works.

**Comment by addshore** [comment]
This is done in mwcli
https://www.mediawiki.org/wiki/Cli
https://phabricator.wikimedia.org/T286677
So closing this as I am no longer maintaining this repo
