### ISSUE TITLE
Use tmpfs for /tmp

### ISSUE THREAD

**Issue by Krinkle** [addshore/mediawiki-docker-dev#123]
Should make things a bit faster, especially when running PHPUnit tests. This will however consume more memory, which increases the chances of mwdd users having to increase their memory allocation for Docker if it no longer fits. I don't know if that's a concern?

**Comment by addshore** [comment]
> I don't know if that's a concern?

I don't think anyone has raised that as a concern yet.
I think speed would be a winner though.
