### ISSUE TITLE
Document the decision to use *.localhost in a markdown doc in the repo

### ISSUE THREAD

**Issue by addshore** [addshore/mediawiki-docker-dev#124]
So it doesn't get lost (as someone just asked why we are not using it)

Detailed in https://github.com/addshore/mediawiki-docker-dev/issues/17

**Comment by Krinkle** [comment]
And upstream bug for Firefox support: https://bugzilla.mozilla.org/show_bug.cgi?id=1220810

(without this, for Firefox, one would still need the one-time setup of adding some entries to your etc-hosts file)
