### ISSUE TITLE
Upgrade PHP

### ISSUE THREAD

**Issue by rlorenzo** [addshore/mediawiki-docker-dev#126]
I tried running this for Mediawiki 1.35 LTS and that requires PHP 7.3.19.

However, loading the docker containers I see that it is running 7.2.24.

How do I upgrade PHP for the containers?

**Comment by rlorenzo** [comment]
Solved it by copying default.env to local.env and changing 

`RUNTIMEVERSION=latest`

to

`RUNTIMEVERSION=7.3`

**Comment by addshore** [comment]
> Solved it by copying default.env to local.env and changing
> 
> `RUNTIMEVERSION=latest`
> 
> to
> 
> `RUNTIMEVERSION=7.3`

I think another option would have been running
`docker pull php:latest`
But this likley would have lead to you using php 8
