### ISSUE TITLE
Install python3 package (support SyntaxHighlight)

### ISSUE THREAD

**Issue by Krinkle** [addshore/mediawiki-docker-dev#127]
After cloning `SyntaxHighlight_GeSHi` and installing it:

```
( ! ) Notice: Failed to invoke Pygments: /usr/bin/env: 'python3': No such file or directory
[Called from SyntaxHighlight::highlightInner
 in /var/www/mediawiki/extensions/SyntaxHighlight_GeSHi/includes/SyntaxHighlight.php at line 316]
```

Fixed after:
```
root@mediawiki:/var/www/mediawiki# apt-get install python3
```

**Comment by addshore** [comment]
This is one of the things that would be better if we move toward custom images somehow (rather than just using the webdev ones)

**Comment by addshore** [comment]
Python3 is installed in the new mwcli & the images used there

![image](https://user-images.githubusercontent.com/3308769/136637506-ebcb337e-106c-4da6-afed-111b46ae82eb.png)
https://www.mediawiki.org/wiki/Cli
