### ISSUE TITLE
Unable to install php packages with new "official php" base image

### ISSUE THREAD

**Issue by Krinkle** [addshore/mediawiki-docker-dev#129]
It seems with the recent changes, the images we now use for PHP are kind of messed up and not so useful because they don't allow for easy installation of php packages in the distro they consume.

I use `RUNTIMEVERSION=7.2` to match WMF production, and I think this used to result in a container where you could do things like `apt-get install php-tideways` and other such packages, and have it actually work.

Now... not so much.

```
root@mediawiki:/var/www/mediawiki# apt-get install php-tideways
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package php-tideways is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php-tideways' has no installation candidate
```

This persists even after doing all the "usual" tricks and updates.

```
root@mediawiki:/var/www/mediawiki# cat /etc/apt/sources.list
deb http://deb.debian.org/debian buster main contrib non-free 

deb http://security.debian.org/debian-security buster/updates main

deb http://deb.debian.org/debian buster-updates main


root@mediawiki:/var/www/mediawiki# apt-get update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease                                               
Hit:3 http://deb.debian.org/debian buster-updates InRelease                                       
Hit:4 https://packages.blackfire.io/debian any InRelease                       
Reading package lists... Done


root@mediawiki:/var/www/mediawiki# apt search tideways
Sorting... Done
Full Text Search... Done
php-tideways/stable 4.1.6-2 amd64
  (none)


root@mediawiki:/var/www/mediawiki# apt-cache showpkg php-tideways
Package: php-tideways
Versions: 
4.1.6-2 (/var/lib/apt/lists/deb.debian.org_debian_dists_buster_main_binary-amd64_Packages.lz4)
Description Language: 
                 File: /var/lib/apt/lists/deb.debian.org_debian_dists_buster_main_binary-amd64_Packages.lz4
                  MD5: 71ce8c8b0e6b853451945195d3e5d48f


Reverse Depends: 
Dependencies: 
4.1.6-2 - ucf (0 (null)) php-common (2 1:7.0+33~) phpapi-20180731 (16 (null)) phpapi-20170718 (0 (null)) libc6 (2 2.17) 
Provides: 
4.1.6-2 - php7.3-tideways (= ) php7.2-tideways (= ) 
Reverse Provides: 
```

It is clearly in the distro channel at <https://packages.debian.org/buster/php-tideways>.

But, it's blocked out by the "php docker community", as per [this FAQ entry](https://github.com/docker-library/docs/tree/b10ac9706270ca71044eb75ccf7158c5124a5a36/php#e-package-php-xxx-has-no-installation-candidate).

The reason being that, they compile PHP as a local binary in `/usr/local/bin` and don't inform apt-get that a php has been installed. Which means, if it weren't for the wildcard `php*` block they put in the image via `/etc/apt/preferences.d/no-debian-php`, then if you would installed `php-tideways` it would install a second copy of php from Debian, in `/usr/local/php`. When using php72 that means this second copy would be php73 since that's what Debian Buster is currently at.

But even if I use RUNTIMEVERSION=7.3, I'd still get a second copy of php.

I don't really understand the purpose of these "official" images, they seem rather custom made and lack almost everything the industry has built over the past decade which webdevops leveraged, but these new official images reinvent the wheel it seems.

I'm happy to adjust to these though, if someone knows a way to get this to work properly with debian packages, though :)

**Comment by Krinkle** [comment]
I can't for the life of me figure out why https://github.com/webdevops/Dockerfile/ and the "php docker community" are trying to compete with Debian, Ubuntu, Sury etc. Why invent everything from scratch with a tiny list of supported extensions, where basically nothing works by default.

For now anyway, I realize that `ubuntu-18` and `debian-10` do still work as a value, and these give you a fullly working and mwdockerdev-integrated setup with php72 or php73 respectively, in a way that doesn't leave `apt-get` broken. E.g. with ubuntu-18 you can install `php-tideways` just fine.

**Comment by addshore** [comment]
So I probably won't try to fix this for this version of mwdd.
I'm working on a golang cli tool along with releng which will contain a new version of mwdd.
This will also be using dev images from the wmf / relengs collections. So we would just need to get the needed tools installable there.
