### ISSUE TITLE
./phpunit hard to use

### ISSUE THREAD

**Issue by Krinkle** [addshore/mediawiki-docker-dev#15]
Usually I run phpunit from the /tests/phpunit directory so that all paths can be provided relative, and so that bash provided auto-completion for any directories or file paths.

The `./phpunit` script runs phpunit via docker's `exec` which doesn't support switching the working directories. I've tried some hackery by making `./phpunit` invoke `sh -c` instead of `php` and switching directories to `//var/www/mediawiki/tests/phpunit` first, but got stuck due to the shell arguments not being passed on properly all the way down. Perhaps you can find a way that works?

Then one can work as follows:

```sh
~$ cd ~/dev/mediawiki/tests/phpunit
.../phpunit$ ~/dev/mediawiki-docker-dev/phpunit --wiki default includes/upload/
# shortcut
.../phpunit$ mw-docker-dev phpunit --wiki default includes/upload/
```

While `//var/www/mediawiki/tests/phpunit` is imho a better default CWD for phpunit than `//`, even better would be to set it based on the real current directory (using `env` `DOCKER_MW_PATH` to map it). A simple prefix search/replace of `DOCKER_MW_PATH` with `//var/www/mediawiki/` would probably cover the common case so it works for `mw/`, `mw/skins`, `mw/tests` and `mw/tests/phpunit` as CWD in the host shell.

At the moment I'm working around it by invoking `./bash` instead and doing it interactively within the container, which is working fine.

**Comment by addshore** [comment]
So I end up running commands like:

`mw-docker-dev phpunit --wiki default //var/www/mediawiki/tests/phpunit/includes/RevisionIntegrationTest.php`

where mw-docker-dev is a bash alias to run commands in the dir of this repo.

For me having mediawiki in an easy directory such as /mw or /mediawiki (or just a symlink) would make running tests easier.

It would make sense to have the phpunit command also already have the CWD of tests/phpunit! :)

**Comment by Krinkle** [comment]
Yeah, the problem with needing to pass `//var/www/mediawiki` is that you'd be typing that from a shell context (the host computer) where that path doesn't exist, so there's no bash completion.

If it would expand the context relative to `mediawiki/tests/phpunit` (or just `mediawiki/`) then, as long as you're in the same directory on the host, it would "just work".

I'd prefer `tests/phpunit`, but I can also imagine that being annoying if you want to run tests for skins or extensions, so `mediawiki/` would make a better default, but either way, I think once we figure out a way to set the CWD for this command, we can make it work both ways based on the current bash CWD (e.g. if it starts with `DOCKER_MW_PATH`, just find/replace that part with `//var/www/mediawiki/` and use the same CWD on the guest for that script run).
