### ISSUE TITLE
Switch from wmftest.net to *.localhost

### ISSUE THREAD

**Issue by Krinkle** [addshore/mediawiki-docker-dev#17]
Sorry for proposing another base-hostname switch, especially after we just finished one.

I think we should adopt use of `*.localhost`.

Firstly, it will mean that in Chrome (and soon Firefox), we won't need any DNS entries given these will resolve within the browser itself (for security reasons).

Secondly, given we lack HTTPS, use of `localhost` is the only way to have the responses treated as a secure context, which enables various web features (Service Workers, Push notifications, Geo location etc) that are otherwise disabled, making it less useful as a development environment.

Browsers have an exception for localhost and `*.localhost`. The reservation of this TLD has been approved years ago and browsers and OS are only starting now with the implementation.

<https://en.wikipedia.org/wiki/.localhost>

**Comment by Krinkle** [comment]
I've got an initial working version of this at:

<https://github.com/Krinkle/mediawiki-docker-dev/tree/d083725c2fb81bd5cb6a8ae182f4bfe00a1dbe3c>

My fork removes the `addhost` command for now. Given the time it takes to run separately with `sudo`, I might as well copy/paste directly into that file.

But would be nice to invest in a scripted solution as well. More info on that at https://github.com/addshore/mediawiki-docker-dev/issues/13

**Comment by addshore** [comment]
So this came up today again, and i'm pretty sure the move to .localhost is a painpoint when trying to run browser tests against this setup.
Chrome will always resolve *.localhost to localhost...
Which means that mwdd can not make the browser resolve these to the nginx proxy per our own dns server....

Having any other tld thing used here would likely get rid of this issue.
Or some way of turning this off in chrome..

**Comment by Krinkle** [comment]
@addshore I don't understand. How you are you running the browser tests? Why is it a problem that it points to localhost?

I'm using mediawiki-docker-dev and run unit tests and browser tests fine, both outside the container (using the localhost URL) and from within a (different) container using fresh-node which knows the localhost subdomain based on MW_SERVER env, and is able to reach it also given `-net` flag to allow networking between containers.

The needed ports are exposed in mwdd afaik. Maybe there's something macOS-specific that is making this work for me?

**Comment by addshore** [comment]
> @addshore I don't understand. How you are you running the browser tests? Why is it a problem that it points to localhost?
> 
> I'm using mediawiki-docker-dev and run unit tests and browser tests fine, both outside the container (using the localhost URL) and from within a (different) container using fresh-node which knows the localhost subdomain based on MW_SERVER env, and is able to reach it also given `-net` flag to allow networking between containers.

Interesting.
Could you talk a bit more about the fresh & mwdd situation?
I don't think any of us over at wmde use fresh to run the browser tests right now.

Does fresh internally use chrome or some other browser?

> The needed ports are exposed in mwdd afaik.

Yup

> Maybe there's something macOS-specific that is making this work for me?

I can confirm that https://stackoverflow.com/questions/39666979/chrome-ignoring-hosts-file-for-subdomains-of-localhost is indeed the issue (at least for running the browser tests using an image like `selenium/standalone-chrome`.

Changing to *.local which I did in a branch at https://github.com/addshore/mediawiki-docker-dev/commit/4f1ff5e558ee88d329e9d39d358fe57f901cc181 would resolve this issue.

This is a learning I'll be sure to take forward with the new version of mwdd inside of mwcli. I won't be using localhost there.

**Comment by addshore** [comment]
I guess within fresh you target the "web" container directly?
targeting "default.web.mw.localhost:8080" though probably doesn't work?

**Comment by Krinkle** [comment]
I use `MW_SERVER=http://default.web.mw.localhost:8080` and then run `fresh -net -env` and run selenium tests there. It just works for me. Headless Chrome and Firefox. Both through selenium/chromium within the container as well as outside of that through my browser.

Does <http://default.web.mw.localhost:8080> work for you when using Chrome normally from your desktop when mwdd is running? If so, why would it be different from a browser inside a container (assuming said container may see the host network).

**Comment by addshore** [comment]
> I use `MW_SERVER=http://default.web.mw.localhost:8080` and then run `fresh -net -env` and run selenium tests there. It just works for me. Headless Chrome and Firefox. Both through selenium/chromium within the container as well as outside of that through my browser.

I'll have to give this a go

> Does http://default.web.mw.localhost:8080 work for you when using Chrome normally from your desktop when mwdd is running? If so, why would it be different from a browser inside a container (assuming said container may see the host network).

Yes
But my docker runs in a VM, and docker "magically" deals with making my localhost ports etc map to the correct places wherever docker actually is.
If you are asking for `localhost` from within a container, you are not expected to get your actual host.
I think the "issue" is that this old branch that was setup for browser tests is trying to use *.localhost, but running in a container that is not on `--network=host`, thus localhost for chrome in the container ends up being the container not the actual host.
