### ISSUE TITLE
XDebug not latest version

### ISSUE THREAD

**Issue by Krinkle** [addshore/mediawiki-docker-dev#25]
The `-dev` Dockerfile for php-dev seems to use `pecl install xdebug`, and per https://pecl.php.net/package/xdebug the latest version is 2.5.5.

Yet, when I check phpinfo, it shows version 2.4.0

```
php -i | grep xdebug -A1 | grep Version
Version => 2.4.0
```

Not sure yet what's causing this.

**Comment by addshore** [comment]
Looks like I have the latest (for php 7.1 that is)

root@1d2a89d9a26b:/# php --version
PHP 7.1.9 (cli) (built: Sep  8 2017 03:07:13) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

Are your images up to date?
Perhaps up should tell you if your images are out of date, not sure how hard that would be.

**Comment by Krinkle** [comment]
Hm.. I thought I did a down/up. I guess that was longer ago than I thought?

Actually, no I just did another `down`/`up`, but made no difference. How do I update the images?

**Comment by Krinkle** [comment]
I tried `docker-compose pull` which indeed appears to have fetched various updates. But after that, `down` and `up` still produced the same:

```
Running bash on the webserver
root@cd30661c1021:/# php --version
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```


env:
```
DB=mariadb
WEBSERVER=apache
PHPORHHVM=php
RUNTIMEVERSION=latest

IDELOCALHOST=10.0.75.1

DOCKER_MW_PATH=~/dev/git/gerrit/mediawiki
DOCKER_MW_PORT=8080
DOCKER_MW_PATH=~/Development/mediawiki
DOCKER_MW_PORT=8181

DOCKERPHPDEV=-dev

```

**Comment by Krinkle** [comment]
@addshore Okay, I've figured it out.

I assume you're using `RUNTIMEVERSION=7.1` instead of the default `latest`.  And despite PHP 7.1 being "later" than PHP 7.0, the `latest` tag for webdevops/php really does have PHP 7.0.

Looking at <https://hub.docker.com/r/webdevops/php/tags/> I can see that the filesize of "latest" matches only one other image in the list, namely "ubuntu-16.04".

And per [webdevops/Dockerfile:README](https://github.com/webdevops/Dockerfile/blob/30b494da0158e4927e89b895d748f4fe63648f90/docker/php/README.md), Ubuntu 16.04 comes with PHP 7.0.

I've filed an upstream issue at https://github.com/webdevops/Dockerfile/issues/210.

**Comment by Krinkle** [comment]
Follow upstream issue for more information. Closing this one.
