### ISSUE TITLE
./up: No such file or directory

### ISSUE THREAD

**Issue by itm1960** [addshore/mediawiki-docker-dev#41]
I've just followed these instructions to install docker, docker compose and mediawiki on Lubuntu 16.10, Everything went OK up to Step 5 when I tried to launch the environment using the ./up command. I got "No such file or directory". Can anyone help?

**Comment by addshore** [comment]
Are you in the directory of this repo when you try to run that command?

The script you are trying to run can be seen @ https://github.com/addshore/mediawiki-docker-dev/blob/master/up

**Comment by itm1960** [comment]
I'm in ~/dev/git/gerrit/mediawiki

**Comment by addshore** [comment]
Thats the wrong directory, you need to be in the directory of this repository, / wherever you cloned it to in step 2 of the README

**Comment by itm1960** [comment]
Ah OK that'll be /home/myuser/mediawiki-docker-dev - thanks. 
Forgive my ignorance - I'm a Linux novice - but having successfully run that how do I start the mediawiki site? (the http://default.web.mw.localhost:8080/ URL returns a blank page)

**Comment by addshore** [comment]
What was the output of the up script? did you see any errors?

Have you done step 4 of the readme? creating a LocalSettings.php file in ~/dev/git/gerrit/mediawiki ?

**Comment by itm1960** [comment]
Yes I created the LocalSettings.php in ~/dev/git/gerrit/mediawiki 
Looking through the output from the ./up command I've just seen this:

```
Running composer install on the web container
If the process hangs here make sure your not listening for debug connections...
Composer could not find a composer.json file in /var/www/mediawiki
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

```

**Comment by addshore** [comment]
Ahhh I think the README is slightly out of date, right.

You have cloned mediawiki to ~/dev/git/gerrit/mediawiki
However the code is looking for it in  /srv/dev/git/gerrit/mediawiki per https://github.com/addshore/mediawiki-docker-dev/blob/master/default.env

You should:
 - Create a local.env file next to the default.env file with the line `DOCKER_MW_PATH=/home/USERNAME/dev/git/gerrit/mediawiki`
- run `./down`
- run `./up` again

Should work! :)
I'll update the README now

**Comment by addshore** [comment]
Updated the readme in https://github.com/addshore/mediawiki-docker-dev/commit/28f665d0ed974727c65067434a99e49d765e8cd2#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by itm1960** [comment]
Thanks. I just added that local.env alongside the default.env in /home/MYUSER/mediawiki-docker-dev, ran /.down & ./up but still get a blank page from http://default.web.mw.localhost:8080/ 

I also get the same error from the ./up command:
```
Running composer install on the web container
If the process hangs here make sure your not listening for debug connections...
Composer could not find a composer.json file in /var/www/mediawiki
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

**Comment by addshore** [comment]
Hmmm, okay I'm not sure sure what is happening here.

What happens if you do the following:
 - Run the `./bash` command which should load bash in the webserver container.
 - Then run `ls /var/www/mediawiki` in the webserver container, what is the output? You should see mediawiki files here, if you don't something has gone wrong.

**Comment by itm1960** [comment]
I see 2 directories listed - images and vendor

**Comment by addshore** [comment]
Okay, so your mediawiki code is not being loaded correctly.

Can you send me the content of the generated .env file that you should find in the mediawiki-docker-dev directory after running `./up` ?

**Comment by itm1960** [comment]
Here's the default.env from that directory:
```
DB=mariadb
WEBSERVER=apache
PHPORHHVM=php
RUNTIMEVERSION=latest

IDELOCALHOST=10.0.75.1

DOCKER_MW_PATH=/srv/dev/git/gerrit/mediawiki
DOCKER_MW_PORT=8080
COMPOSER_CACHE_PATH_OR_VOL=composer-cache
```

**Comment by addshore** [comment]
Not the default.env, there should also be a `.env` file generated when you run `./up`.
When in the directory just type `cat .env` and you should get the content of the file.

**Comment by itm1960** [comment]
Here's the output from cat .env:
```
DB=mariadb
WEBSERVER=apache
PHPORHHVM=php
RUNTIMEVERSION=latest

IDELOCALHOST=10.0.75.1

DOCKER_MW_PATH=/srv/dev/git/gerrit/mediawiki
DOCKER_MW_PORT=8080
COMPOSER_CACHE_PATH_OR_VOL=composer-cache
DOCKER_MW_PATH=/home/MYUSER/dev/git/gerrit/mediawiki
DOCKERPHPDEV=-dev
```

**Comment by addshore** [comment]
You have to change `MYUSER` to your username on your machine in your `local.env` file ;)

When in your `mediawiki` directory type `pwd`. The output of that command is what you want to put on the `DOCKER_MW_PATH=` line in your `local.env` :)

**Comment by addshore** [comment]
then try `./down` and `./up` again

**Comment by itm1960** [comment]
Yes I did remove my username when I posted the original .env file! 
So I edited local.env to change DOCKER_MW_PATH to the value returned by ```pwd``` in my mediawiki directory. Did ```./down``` and ```./up``` and still get a blank page from the default URL (and the same message about the composer.json file). Here's the new .env:
```
DB=mariadb
WEBSERVER=apache
PHPORHHVM=php
RUNTIMEVERSION=latest

IDELOCALHOST=10.0.75.1

DOCKER_MW_PATH=/srv/dev/git/gerrit/mediawiki
DOCKER_MW_PORT=8080
COMPOSER_CACHE_PATH_OR_VOL=composer-cache
DOCKER_MW_PATH=/home/MYUSER/mediawiki-docker-dev
DOCKERPHPDEV=-dev
```

**Comment by addshore** [comment]
You have confused the 2 repos / dirs again in the comment above

`/home/MYUSER/mediawiki-docker-dev` is your mediawiki-docker-dev directory, not the mediawiki directory.

**Comment by itm1960** [comment]
Sorry to be dumb...so is my mediawiki directory ```/var/www/mediawiki``` or ```/srv/dev/git/gerrit/mediawiki```. Or somewhere else?

**Comment by addshore** [comment]
It is wherever you cloned it to in step 3 of the README :)

When you read the readme this will has suggested `~/dev/git/gerrit/mediawiki` however that change to `/srv/dev/git/gerrit/mediawiki` with the alteration that I made above to fix the readme :)

**Comment by itm1960** [comment]
Yes I went with the suggestion of ```~/dev/git/gerrit/mediawiki```
Ok I now have a mediawiki page (although it's telling me that the default skin isn't available, which I'll need to investigate...) - thanks!
Can this wiki be accessed from other machines on the LAN? (I couldn't work out what the URL would be!)

**Comment by addshore** [comment]
@itm1960 that depends on your docker setup really, and many other things!

To fix that message you just need to add `wfLoadSkin( 'Vector' );` into your LocalSettings.php :) You don't need to rerun everything or run anything, the config will be updated straight away and a reload of the page should reflect that.

Thanks for troubling your way through this and getting me to update the README!

**Comment by itm1960** [comment]
Many thanks for helping me through this. I'm not having much luck today...so I added ```wfLoadSkin( 'Vector' );``` to  ```~/dev/git/gerrit/mediawiki/LocalSettings.php```, but a refresh of the page still gives me the error message about the missing skin. Have I got the wrong directory again?

**Comment by itm1960** [comment]
The message I see is:
```
Whoops! The default skin for your wiki, defined in $wgDefaultSkin as vector, is not available.

Your installation seems to include the following skin. See Manual: Skin configuration for information how to enable it.

    vector / Vector (disabled)
```

**Comment by addshore** [comment]
Ahh, you also need to clone the Vector skin!

In your mediawiki directory you have a directory called `skins` and you need to clone Vector to there!

You can get Vector from gerrit @ https://gerrit.wikimedia.org/r/#/admin/projects/mediawiki/skins/Vector (youll find the pull command there)

**Comment by itm1960** [comment]
It's OK I found another ```LocalSettings.php``` to edit, in ```/home/MYUSER/mediawiki-docker-dev/config/mediawiki/LocalSettings.php```. When I added ```wfLoadSkin( 'Vector' );``` to that file and refreshed the page the error message about the skin disappeared. 
Was that a legitimate way to fix the problem?

**Comment by addshore** [comment]
That is the wrong local settings, you should change the localsettings that you would normally edit with mediawiki!

You'll find this in you mediawiki directory.

It is the file that you created in step 4 of the README
(you should change the other localsettings file you just changed back ;)

**Comment by itm1960** [comment]
Hmmm...TBH I'm still not clear on which directory is my mediawiki directory! (I edited more than one ```LocalSettings.php``` file before I found the right one. To recap - I cloned the repository using this command from Step 2:
```git clone https://github.com/addshore/mediawiki-docker-dev.git```

I then cloned mediawiki and the vector skin using these commands from Step 3:
```git clone https://gerrit.wikimedia.org/r/mediawiki/core /srv/dev/git/gerrit/mediawiki
git clone https://gerrit.wikimedia.org/r/mediawiki/skins/Vector /srv/dev/git/gerrit/mediawiki/skins/Vector
```
In Step 4 I then wasn't sure where the root of the mediawiki repo was, so tried editing LocalSettings.php in a few places until I hit on the one that worked (!).

Given the above, where would I expect my mediawiki directory to be? (i.e. the one where I need to edit the ```LocalSettings.php``` file?

**Comment by itm1960** [comment]
...sorry this was the command that I used in Step 2 to clone mediawiki:
```git clone https://gerrit.wikimedia.org/r/mediawiki/core /srv/dev/git/gerrit/mediawiki```

**Comment by addshore** [comment]
> ...sorry this was the command that I used in Step 2 to clone mediawiki:
> git clone https://gerrit.wikimedia.org/r/mediawiki/core /srv/dev/git/gerrit/mediawiki

If you used that command then `/srv/dev/git/gerrit/mediawiki` is the location of you mediawiki directory.

**Comment by itm1960** [comment]
OK I've added that line to ```/srv/dev/git/gerrit/mediawiki/LocalSettings.php```, and undone my original edit to ```/home/MYUSER/mediawiki-docker-dev/config/mediawiki/LocalSettings.php```

Now when I run ./down to stop the server I'm getting an error:
```Containers & Volumes are being pulled down
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

I had been trying (unsuccessfully) to expose docker port 8080 to the host, so that I could access the mediawiki site from another machine, and had tried the commands below. Have I broken something?
```
sudo docker run -d -p 8080:8080 apache
Unable to find image 'apache:latest' locally
docker: Error response from daemon: pull access denied for apache, repository does not exist or may require 'docker login'.
```
```
sudo docker run -d -p 8080:8080 nginx
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
e7bb522d92ff: Already exists 
6edc05228666: Already exists 
cd866a17e81f: Already exists 
Digest: sha256:285b49d42c703fdf257d1e2422765c4ba9d3e37768d6ea83d7fe2043dad6e63d
Status: Downloaded newer image for nginx:latest
76c5465da14e541c25c597ea1e7a043bbae94371b8deb9abbcd740cd9e69486e
docker: Error response from daemon: driver failed programming external connectivity on endpoint nervous_hypatia (2ea41cfb25632e9d0425634c05c86817e3ebe683ab40fc62fa6f5e99bf6d16e1): Bind for 0.0.0.0:8080 failed: port is already allocated.
```

```
sudo docker run -d -p 8080:8080 mediawikidockerdev_web_1
Unable to find image 'mediawikidockerdev_web_1:latest' locally
docker: Error response from daemon: pull access denied for mediawikidockerdev_web_1, repository does not exist or may require 'docker login'.
See 'docker run --help'
```

```
sudo docker run -d -p 8080:8080 mediawikidockerdev_nginx-proxy_1
Unable to find image 'mediawikidockerdev_nginx-proxy_1:latest' locally
docker: Error response from daemon: pull access denied for mediawikidockerdev_nginx-proxy_1, repository does not exist or may require 'docker login'.
```

**Comment by addshore** [comment]
> ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

That looks like docker isn't running now, or you have broken docker somehow!

> sudo docker run -d -p 8080:8080 apache

That image doesn't exist, and i dont think a command like that will do what you are trying to do.

The ./up command already maps 8080:80 for the mediawiki webserver, hence why mediawiki is accessible on port 8080 on localhost.

What exactly are you trying to do?

**Comment by itm1960** [comment]
Hmmm I feared I may have messed something up....basically I'm trying to enable access to the mediawiki/docker application from other machines on the network. The machine currently also hosts a homeassistant server (not a docker deployment) which provides a web console on port 7474, and I hoped that exposing docker's 8080 port to the host O/S would enable remote access to the new mediawiki site. 
Would it be best to try to uninstall docker and start again do you think?

**Comment by addshore** [comment]
I'm not sure what things you have been poking, but if nothing is working it might be worth a reinstall.

At a guess it should be accessible to other devices, you probably have some firewalls in the way though.
Also, the name lookups wont work, you'll notice going to localhost:8080 you get nothing.

Are you using this for development or something else?

**Comment by itm1960** [comment]
I've tried a reboot, and am now back to getting the ``Composer could not find a composer.json file in /var/www/mediawiki``` message when I run ```./up``` 

So backtracking to our previous conversation, I edited ```/srv/dev/git/gerrit/mediawiki/local.env``` so that it now looks like this:
```
DB=mariadb
WEBSERVER=apache
PHPORHHVM=php
RUNTIMEVERSION=latest

IDELOCALHOST=10.0.75.1

DOCKER_MW_PATH=/srv/dev/git/gerrit/mediawiki
DOCKER_MW_PORT=8080
COMPOSER_CACHE_PATH_OR_VOL=composer-cache
```

...which looks correct to me, but I'm still getting ``Composer could not find a composer.json file in /var/www/mediawiki``` message when I run ```./up``` 

This is for an internal-only wiki site for a few users. I figure there are no networking or firewall issues preventing access to the server from other machines, as I can already access my homeassistant server on port 7474. I guess I can just open port 80 and should get access to mediawiki (if I can get it started)?

**Comment by Krinkle** [comment]
@itm1960 The `.env` files are part of mediawiki-docker-dev and belong in that directory, not `/srv/dev/git/gerrit/mediawiki`. Can you verify that?

**Comment by itm1960** [comment]
Yes I can confirm that the local.env above is from ```~/mediawiki-docker-dev```

**Comment by itm1960** [comment]
Sorry I just realised that my last edit to ```~/mediawiki-docker-dev/local.env``` pointed ```DOCKER_MW_PATH``` to the wrong location.  I've corrected it to ```DOCKER_MW_PATH=/home/MYUSER/dev/git/gerrit/mediawiki``` but am still getting that ```Composer could not find a composer.json file in /var/www/mediawiki``` error when I restart the container

**Comment by addshore** [comment]
> So backtracking to our previous conversation, I edited /srv/dev/git/gerrit/mediawiki/local.env

That is again the wrong file.
the *.env files are in the mediawiki-docker-dev directory which is your clone of this repo.

> This is for an internal-only wiki site for a few users

If it is not for development then you really shouldn't be using this setup.
See: https://hub.docker.com/_/mediawiki/

You have had the setup working once, I am not sure what you have done to break it :/
All I can suggest is to read the README, as the steps there work.
You seem to be mixing up the mediawiki directory (the directory containing mediawiki code) and the mediawiki-docker-dev directory (the directory that contains the clone of this repo) quite a lot, and I imagine you just have something pointing to the wrong place.

Also, if you are running docker for windows, you could be running into an issue where volume mounts don't work at all (a bug in a recent update) and you'll need to update again to get anything working.

**Comment by itm1960** [comment]
Thanks for your reply - yes I'll investigate an alternative setup.
