### ISSUE TITLE
./down + ./up: Fails at Creating images directory (File exists)

### ISSUE THREAD

**Issue by Krinkle** [addshore/mediawiki-docker-dev#44]
```
$ ./up
Creating mediawikidockerdev_phpmyadmin_1      ... done
Creating mediawikidockerdev_db-master_1       ... done
Creating mediawikidockerdev_phpmyadmin_1      ... 
Creating mediawikidockerdev_nginx-proxy_1     ... done
Creating mediawikidockerdev_db-slave_1        ... 
Creating mediawikidockerdev_nginx-proxy_1     ... 
Creating mediawikidockerdev_graphite-statsd_1 ... 
Creating mediawikidockerdev_web_1             ... done
Creating mediawikidockerdev_web_1             ... 
Waiting for the db servers to finish starting
wait-for-it.sh: waiting 15 seconds for db-master:3306
wait-for-it.sh: db-master:3306 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for db-slave:3306
wait-for-it.sh: db-slave:3306 is available after 0 seconds
Setting up log directory
Setting up images directory
Adding new site: default
Creating images directory
mkdir: cannot create directory ‘//var/www/mediawiki/images/docker/default’: File exists
```

I made sure to run `./down` and `docker-compose down` and `docker-compose down --remove-orphans`, and do so from both the old branch and the latest master. But it still fails.

Looks like the problem is that `down` doesn't remove it, and yet `up` insists on being able to create it from scratch. So we should either decide to remove it from `down` or make `up` tolerate if it already exists. I'd prefer the latter.

**Comment by addshore** [comment]
hmm, down should remove all volumes https://github.com/addshore/mediawiki-docker-dev/blob/master/down#L5
And the images directory, or at least the docker sub directory is a volume https://github.com/addshore/mediawiki-docker-dev/blob/master/docker-compose.yml#L70
And this sub directory is where the images are created https://github.com/addshore/mediawiki-docker-dev/blob/master/addsite#L7

we could make the mkdir calls ignore directories when they already exist, but that doesn't seem like the right fix here.

**Comment by tarrow** [comment]
The skip on directories already existing might be needed because otherwise if they already exist (for example the developer mounts them in) then addsite fails early (and almost silently)

**Comment by nyurik** [comment]
I'm running into the same issue

**Comment by Krinkle** [comment]
Another way to trigger it is when you've already up'ed your install and, on a subsequent day, you accidentally run `./up` instead of `./start`. The result is re-creation of most stuff (fine..) but before the last step(s), it aborts with this error.

From what I could tell, everything worked after that, but it'd be nice to either stop early and do nothing at all, or to have it work all the way.

**Comment by nyurik** [comment]
Can `up` and `start` be merged into one?

**Comment by addshore** [comment]
> Can up and start be merged into one?

Maybe, perhaps it should be a little cleverer and check to see if the containers are already setup? and then decide exactly what to do after that point.

**Comment by addshore** [comment]
Im guessing this is no longer an issue as the script now does mkdir -p ?

https://github.com/addshore/mediawiki-docker-dev/blob/f5a5c484ce3c7170c0080b9c6efe02a52e504c98/addsite#L7

Fixed in https://github.com/addshore/mediawiki-docker-dev/commit/5fb637a9d8dd6e7f5307d1a2759274f6d93d4e2b#diff-93b92a60af21d853783bd23e4b122773
