### ISSUE TITLE
Error message from ./logs-tail (stale, no updates)

### ISSUE THREAD

**Issue by Krinkle** [addshore/mediawiki-docker-dev#45]
Whenever I run `./logs-tail debug.log` three things happen:

1. There is valid output (yay).

2. It ends with error message `tail: unrecognized file system type 0x794c7630 for ‘../../log/mediawiki/debug.log’. please report this to bug-coreutils@gnu.org. reverting to polling`

3. No further output appears from subsequent requests. Even restarting the logs-tail, won't make new output show up.

Took me a while to figure out, as I was specifically trying to reproduce a bug that results in an error message being logged and it wasn't appearing.

I had to delete the file, and restart the docker containers to make new output show up. But after that it's static again. So it seems as if once the file is inspected by tail, it is stuck with that impression for the remainder of the container's lifetime.

There seem to be many reports about this on the web (issues with docker volume and tail)

* <https://www.google.co.uk/search?q=tail+%22unrecognized+file+system+type%22+docker>
* <https://stackoverflow.com/a/42618921/319266>

Some reports say this was fixed in coreutils 8.24 (e.g Debian Stretch or Ubuntu Xenial and higher). But that doesn't seem to be the case given I'm using Ubuntu Xenial (coreutils 8.25).

The StackOverflow link provides a possible work around by running it via `sh -c`. Might be worth a try.

**Comment by addshore** [comment]
I'm not going to actively fix this in mediawiki-docker-dev.

This is much easier in https://www.mediawiki.org/wiki/Cli

![image](https://user-images.githubusercontent.com/3308769/136637425-a5ebfdfd-bf16-4062-a41a-4d72b699c703.png)
