### ISSUE TITLE
Multiple wikis with wildcard domains

### ISSUE THREAD

**Issue by Krinkle** [addshore/mediawiki-docker-dev#5]
You may be able to add a setup script that runs outside Docker to install a dns service that routes something like `*.mw.dev` to localhost.

Alternatively, you can also use the longer `*.local.wmftest.net` space which is publicly hosted to route to 127.0.0.1 for this very purpose and currently used by MediaWiki-Vagrant in the same way. 

However, aside from browser dns caching, this will not work when offline, which is unfortunate.

Perhaps you can ship a setup script that asks for sudo and then populates a section in `/etc/hosts` with all known combinations as currently installed. Then people will only need to re-run the script when they create new variants.

Using wmftest has the benefit of working without the setup script and makes it an optional step. On the other hand, if we're scripting set-up anyway, might as well pick a shorter name (like `mw.dev`) and just make it mandatory. E.g. `bin/refresh-hosts` or some such.

**Comment by addshore** [comment]
I like the idea of *.local.wmftest.net and wild card domains in general.
I haven't yet looked into a dns service to resolve domains and wildcard domains but I really like the idea.
Adding auto population of the hosts file is on the todo list.

**Comment by gbirke** [comment]
Just to throw some ideas in here:
- You could use [docker-gen](https://github.com/jwilder/docker-gen) to generate the /etc/hosts file
- You could also use [registrator](http://gliderlabs.github.io/registrator/latest/) and [Consul](https://www.consul.io). Consul has a builtin DNS interface so you only have to add it as an additional DNS provider.

**Comment by addshore** [comment]
So, wildcard domains are not setup, but when adding a site it will automatically get added to the hosts file.

So for example I can do:

`
up
addsite test1
addshore test2
`

Which will result in the following entries in the hosts file:

```
127.0.0.1 default.web.mw.local # mediawiki-docker-dev
127.0.0.1 test1.web.mw.local # mediawiki-docker-dev
127.0.0.1 test2.web.mw.local # mediawiki-docker-dev
```

**Comment by Krinkle** [comment]
Closing in favour of https://github.com/addshore/mediawiki-docker-dev/issues/17.

Adding separate entries to `/etc/hosts` seems fine as far as I'm concerned. Certainly better than running a DNS resolver on the host OS, in my opinion.

Once we switch to `*.localhost` and most browsers implement it, one might even forego this step entirely.

Either way, in current master this is already the case (as long as you're online) given wmftest.net is a wildcard already. So running `addsite` but skipping `addhost` already works.
