### ISSUE TITLE
PHP > 7.0

### ISSUE THREAD

**Issue by JeroenDeDauw** [addshore/mediawiki-docker-dev#58]
I just noticed this docker stuff is running PHP 7.0, which does not work for my PHP 7.1 using extension. How can I run with PHP 7.2?

**Comment by Krinkle** [comment]
Create or edit your `local.env` file and set `RUNTIMEVERSION` to a value of your choosing.

mediawiki-docker-dev uses the base images provided by @webdevops. Any of theirs will work.

See also [readme](https://github.com/addshore/mediawiki-docker-dev#6-configure-the-environment), and (in my fork) [annotated env](https://github.com/Krinkle/mediawiki-docker-dev/blob/0a70e81c01cd365ac880b044753e4881abee7b8a/default.env#L18-L29).

**Comment by JeroenDeDauw** [comment]
Huzzah!
![image](https://user-images.githubusercontent.com/146040/43353402-a050c9cc-9238-11e8-921a-a37a765ddd7a.png)
