### ISSUE TITLE
Clarify location of the local.env

### ISSUE THREAD

**Issue by nyurik** [addshore/mediawiki-docker-dev#60]
In README, this line is unclear where `local.env` should be placed:

> Copy the content of default.env from the mediawiki-docker-dev dir into a new file called local.env.

**Comment by Krinkle** [comment]
Fixed in https://github.com/addshore/mediawiki-docker-dev/commit/e575107917fed679a6fe8ede7fc5609d0dd7dc33 and https://github.com/addshore/mediawiki-docker-dev/commit/d34d522a50b06eb504e84f77e116b3c637fac12d.
