### ISSUE TITLE
Document access to phpmyadmin

### ISSUE THREAD

**Issue by nyurik** [addshore/mediawiki-docker-dev#64]
It is not clear what account should be used when accessing phpmyadmin site. I tried `wikiuser` without the password, but that didn't work.

**Comment by addshore** [comment]
Yup, there were env vars for phpmyadmin that would auto fill the login details / auto log you in at some point, but for some reason that has broken...

**Comment by nyurik** [comment]
I found the password! :)  toor!

**Comment by addshore** [comment]
Will not be done in this repo, but will be done for mwcli mwdd
