### ISSUE TITLE
Error on ./up: "Could not wait for replica DBs to catch up to db-master"

### ISSUE THREAD

**Issue by cdrini** [addshore/mediawiki-docker-dev#67]
Here is the last bit of log:

```
Your composer.lock file is up to date with current dependencies!
Going to run database updates for default
Depending on the size of your database this may take a while!
Turning off Content Handler DB fields for this part of upgrade.
[00704eac7e08448f1f9a0778] [no req]   Wikimedia\Rdbms\DBReplicationWaitError from line 436 of /var/www/mediawiki/includes/libs/rdbms/lbfactory/LBFactory.php: Could not wait for replica DBs to catch up to db-master
Backtrace:
#0 /var/www/mediawiki/includes/installer/DatabaseUpdater.php(487): Wikimedia\Rdbms\LBFactory->waitForReplication()
#1 /var/www/mediawiki/includes/installer/DatabaseUpdater.php(447): DatabaseUpdater->runUpdates(array, boolean)
#2 /var/www/mediawiki/maintenance/update.php(200): DatabaseUpdater->doUpdates(array)
#3 /var/www/mediawiki/maintenance/doMaintenance.php(94): UpdateMediaWiki->execute()
#4 /var/www/mediawiki/maintenance/update.php(245): require_once(string)
#5 {main}
```

Note I'm running Windows with Docker Toolbox, if that has an effect on anything.

**Comment by addshore** [comment]
If you are using Windows then make sure that you have pulled the latest copy of master!

I also use Windows and fixed an issue with permissions causing mysql replication to fail in https://github.com/addshore/mediawiki-docker-dev/pull/59

**Comment by cdrini** [comment]
I have the latest version: fea8877
Does your Windows support Hyper-V? I have Home Edition, so I have to use Docker Toolbox instead of Hyper-V Docker.

**Comment by addshore** [comment]
Ahh yes I am using HyperV.

What are the permissions of the files in /etc/mysql/conf.d/ in your db containers?
You should be able to get this by using the following commands while in the directory of this repo.

```
docker-compose exec "db-master" sh -c "ls -la /etc/mysql/conf.d/"
docker-compose exec "db-slave" sh -c "ls -la /etc/mysql/conf.d/"
```

Also please paste the logs of the "db-configure" container which should not be running but is what sets up the replication initially:

`docker-compose logs db-configure`

If you want a quick work around take a look at the "masterOnly" branch that I just created for you.
If we don't manage to get to the bottom of your issue in "good time" then I'll make a master only setup a feature with a feature flag.

**Comment by cdrini** [comment]
Here are the resulting outputs:

<pre><details open><summary>$ docker-compose exec "db-master" sh -c "ls -la /etc/mysql/conf.d/"</summary>
total 12
drwxr-xr-x 2 root root 4096 Aug 28 19:57 .
drwxr-xr-x 5 root root 4096 Aug 26 18:37 ..
-r--r--r-- 1 root root  182 Aug 28 19:57 master.cnf
</details></pre>

<pre><details open><summary>$ docker-compose exec "db-slave" sh -c "ls -la /etc/mysql/conf.d/"</summary>
total 12
drwxr-xr-x 2 root root 4096 Aug 28 19:57 .
drwxr-xr-x 5 root root 4096 Aug 26 18:37 ..
-r--r--r-- 1 root root  203 Aug 28 19:57 slave.cnf
</details></pre>

<pre><details><summary>$ docker-compose logs db-configure</summary>
Attaching to mediawikidockerdev_db-configure_1
db-configure_1     | ++ dirname /tmp/mysql_connector.sh
db-configure_1     | + BASE_PATH=/tmp
db-configure_1     | + echo 'Waiting for mysql to get up'
db-configure_1     | Waiting for mysql to get up
db-configure_1     | + /tmp/wait-for-it.sh db-master:3306
db-configure_1     | wait-for-it.sh: waiting 15 seconds for db-master:3306
db-configure_1     | wait-for-it.sh: timeout occurred after waiting 15 seconds for db-master:3306
db-configure_1     | + /tmp/wait-for-it.sh db-slave:3306
db-configure_1     | wait-for-it.sh: waiting 15 seconds for db-slave:3306
db-configure_1     | wait-for-it.sh: timeout occurred after waiting 15 seconds for db-slave:3306
db-configure_1     | + /tmp/wait-for-it.sh db-master:3306
db-configure_1     | wait-for-it.sh: waiting 15 seconds for db-master:3306
db-configure_1     | wait-for-it.sh: db-master:3306 is available after 2 seconds
db-configure_1     | + /tmp/wait-for-it.sh db-slave:3306
db-configure_1     | wait-for-it.sh: waiting 15 seconds for db-slave:3306
db-configure_1     | wait-for-it.sh: db-slave:3306 is available after 2 seconds
db-configure_1     | + echo 'Create MySQL Servers (master / slave repl)'
db-configure_1     | Create MySQL Servers (master / slave repl)
db-configure_1     | + echo -----------------
db-configure_1     | -----------------
db-configure_1     | + echo '* Create replication user'
db-configure_1     | * Create replication user
db-configure_1     | + mysql --host db-slave -uroot -ptoor -AN -e 'STOP SLAVE;'
db-configure_1     | + mysql --host db-slave -uroot -ptoor -AN -e 'RESET SLAVE ALL;'
db-configure_1     | + mysql --host db-master -uroot -ptoor -AN -e 'CREATE USER '\''repl'\''@'\''%'\'';'
db-configure_1     | + mysql --host db-master -uroot -ptoor -AN -e 'GRANT REPLICATION SLAVE ON *.* TO '\''repl'\''@'\''%'\'' IDENTIFIED BY '\''repl'\'';'
db-configure_1     | + mysql --host db-master -uroot -ptoor -AN -e 'flush privileges;'
db-configure_1     | + echo '* Set MySQL01 as master on MySQL02'
db-configure_1     | * Set MySQL01 as master on MySQL02
db-configure_1     | ++ eval 'mysql --host db-master -uroot -ptoor -e '\''show master status \G'\'' | grep Position | sed -n -e '\''s/^.*: //p'\'''
db-configure_1     | +++ sed -n -e 's/^.*: //p'
db-configure_1     | +++ grep Position
db-configure_1     | +++ mysql --host db-master -uroot -ptoor -e 'show master status \G'
db-configure_1     | + MYSQL01_Position=768
db-configure_1     | ++ eval 'mysql --host db-master -uroot -ptoor -e '\''show master status \G'\''     | grep File     | sed -n -e '\''s/^.*: //p'\'''
db-configure_1     | +++ sed -n -e 's/^.*: //p'
db-configure_1     | +++ grep File
db-configure_1     | +++ mysql --host db-master -uroot -ptoor -e 'show master status \G'
db-configure_1     | + MYSQL01_File=mysql-bin.000003
db-configure_1     | ++ eval 'getent hosts db-master|awk '\''{print $1}'\'''
db-configure_1     | +++ awk '{print $1}'
db-configure_1     | +++ getent hosts db-master
db-configure_1     | + MASTER_IP=172.19.0.5
db-configure_1     | + echo 172.19.0.5
db-configure_1     | + mysql --host db-slave -uroot -ptoor -AN -e 'CHANGE MASTER TO master_host='\''db-master'\'', master_port=3306,         master_user='\''repl'\'', master_password='\''repl'\'', master_log_file='\''mysql-bin.000003'\'',         master_log_pos=768;'
db-configure_1     | 172.19.0.5
db-configure_1     | + echo '* Set MySQL02 as master on MySQL01'
db-configure_1     | * Set MySQL02 as master on MySQL01
db-configure_1     | ++ eval 'mysql --host db-slave -uroot -ptoor -e '\''show master status \G'\'' | grep Position | sed -n -e '\''s/^.*: //p'\'''
db-configure_1     | +++ sed -n -e 's/^.*: //p'
db-configure_1     | +++ grep Position
db-configure_1     | +++ mysql --host db-slave -uroot -ptoor -e 'show master status \G'
db-configure_1     | + MYSQL02_Position=342
db-configure_1     | ++ eval 'mysql --host db-slave -uroot -ptoor -e '\''show master status \G'\''     | grep File     | sed -n -e '\''s/^.*: //p'\'''
db-configure_1     | +++ sed -n -e 's/^.*: //p'
db-configure_1     | +++ grep File
db-configure_1     | +++ mysql --host db-slave -uroot -ptoor -e 'show master status \G'
db-configure_1     | + MYSQL02_File=mysql-bin.000003
db-configure_1     | ++ eval 'getent hosts db-slave|awk '\''{print $1}'\'''
db-configure_1     | +++ awk '{print $1}'
db-configure_1     | +++ getent hosts db-slave
db-configure_1     | + SLAVE_IP=172.19.0.4
db-configure_1     | + echo 172.19.0.4
db-configure_1     | + mysql --host db-master -uroot -ptoor -AN -e 'CHANGE MASTER TO master_host='\''db-slave'\'', master_port=3306,         master_user='\''repl'\'', master_password='\''repl'\'', master_log_file='\''mysql-bin.000003'\'',         master_log_pos=342;'
db-configure_1     | 172.19.0.4
db-configure_1     | + echo '* Start Slave on both Servers'
db-configure_1     | * Start Slave on both Servers
db-configure_1     | + mysql --host db-slave -uroot -ptoor -AN -e 'start slave;'
db-configure_1     | + echo 'Increase the max_connections to 2000'
db-configure_1     | Increase the max_connections to 2000
db-configure_1     | + mysql --host db-master -uroot -ptoor -AN -e 'set GLOBAL max_connections=2000'
db-configure_1     | + mysql --host db-slave -uroot -ptoor -AN -e 'set GLOBAL max_connections=2000'
db-configure_1     | + mysql --host db-slave -uroot -ptoor -e 'show slave status \G'
db-configure_1     | *************************** 1. row ***************************
db-configure_1     |                 Slave_IO_State: NULL
db-configure_1     |                    Master_Host: db-master
db-configure_1     |                    Master_User: repl
db-configure_1     |                    Master_Port: 3306
db-configure_1     |                  Connect_Retry: 60
db-configure_1     |                Master_Log_File: mysql-bin.000003
db-configure_1     |            Read_Master_Log_Pos: 768
db-configure_1     |                 Relay_Log_File: mysqld-relay-bin.000001
db-configure_1     |                  Relay_Log_Pos: 4
db-configure_1     |          Relay_Master_Log_File: mysql-bin.000003
db-configure_1     |               Slave_IO_Running: Preparing
db-configure_1     |              Slave_SQL_Running: Yes
db-configure_1     |                Replicate_Do_DB: 
db-configure_1     |            Replicate_Ignore_DB: 
db-configure_1     |             Replicate_Do_Table: 
db-configure_1     |         Replicate_Ignore_Table: 
db-configure_1     |        Replicate_Wild_Do_Table: 
db-configure_1     |    Replicate_Wild_Ignore_Table: 
db-configure_1     |                     Last_Errno: 0
db-configure_1     |                     Last_Error: 
db-configure_1     |                   Skip_Counter: 0
db-configure_1     |            Exec_Master_Log_Pos: 768
db-configure_1     |                Relay_Log_Space: 256
db-configure_1     |                Until_Condition: None
db-configure_1     |                 Until_Log_File: 
db-configure_1     |                  Until_Log_Pos: 0
db-configure_1     |             Master_SSL_Allowed: No
db-configure_1     |             Master_SSL_CA_File: 
db-configure_1     |             Master_SSL_CA_Path: 
db-configure_1     |                Master_SSL_Cert: 
db-configure_1     |              Master_SSL_Cipher: 
db-configure_1     |                 Master_SSL_Key: 
db-configure_1     |          Seconds_Behind_Master: NULL
db-configure_1     |  Master_SSL_Verify_Server_Cert: No
db-configure_1     |                  Last_IO_Errno: 0
db-configure_1     |                  Last_IO_Error: 
db-configure_1     |                 Last_SQL_Errno: 0
db-configure_1     |                 Last_SQL_Error: 
db-configure_1     |    Replicate_Ignore_Server_Ids: 
db-configure_1     |               Master_Server_Id: 1
db-configure_1     |                 Master_SSL_Crl: 
db-configure_1     |             Master_SSL_Crlpath: 
db-configure_1     |                     Using_Gtid: No
db-configure_1     |                    Gtid_IO_Pos: 
db-configure_1     |        Replicate_Do_Domain_Ids: 
db-configure_1     |    Replicate_Ignore_Domain_Ids: 
db-configure_1     |                  Parallel_Mode: conservative
db-configure_1     |                      SQL_Delay: 0
db-configure_1     |            SQL_Remaining_Delay: NULL
db-configure_1     |        Slave_SQL_Running_State: Slave has read all relay log; waiting for the slave I/O thread to update it
db-configure_1     |               Slave_DDL_Groups: 0
db-configure_1     | Slave_Non_Transactional_Groups: 0
db-configure_1     |     Slave_Transactional_Groups: 0
db-configure_1     | + echo 'MySQL servers created!'
db-configure_1     | MySQL servers created!
db-configure_1     | + echo --------------------
db-configure_1     | --------------------
db-configure_1     | + echo
db-configure_1     | 
db-configure_1     | + echo Variables available fo you :-
db-configure_1     | Variables available fo you :-
db-configure_1     | + echo
db-configure_1     | 
db-configure_1     | + echo MYSQL01_IP : db-master
db-configure_1     | MYSQL01_IP : db-master
db-configure_1     | + echo MYSQL02_IP : db-slave
db-configure_1     | MYSQL02_IP : db-slave
</details></pre>

-----

The masterOnly branch worked well! I had to also remove the db-slave wait-for-it in ./up ( https://github.com/addshore/mediawiki-docker-dev/blob/masterOnly/up#L38 ). (Note: I had previously increased the wait-for-it timeout for db-master in ./up to 45 sec; it takes 20-35s to startup on my machine). Thanks for creating that branch for me! I don't think I would've been able to get past this without it.

I'm having some issues getting the hosts working right now, but I'll open another ticket for it if I can't figure it out.

**Comment by cdrini** [comment]
In the file that throws the `DBReplicationWaitError`:

https://github.com/wikimedia/mediawiki/blob/f2e9fb2ee04434c631ca60b07c6f061441895f0d/includes/libs/rdbms/lbfactory/LBFactory.php#L425-L436
```php
$failed = [];
foreach ( $lbs as $i => $lb ) {
	if ( $masterPositions[$i] ) {
		// The RDBMS may not support getMasterPos()
		if ( !$lb->waitForAll( $masterPositions[$i], $opts['timeout'] ) ) {
			$failed[] = $lb->getServerName( $lb->getWriterIndex() );
		}
	}
}

if ( $failed ) {
	throw new DBReplicationWaitError(
```

If I could increase that timeout, it might be enough to get this working. 

It looks like timeout is overwritten to ~60 sec [in the same file](https://github.com/wikimedia/mediawiki/blob/f2e9fb2ee04434c631ca60b07c6f061441895f0d/includes/libs/rdbms/lbfactory/LBFactory.php#L378) (since the the calling function in the callstack doesn't provide options).

I tried changing it to 600 seconds in LBFactory.php, but it had no effect. Further investigation shows that the error isn't actually a timeout error at all. There's a null $status here: https://github.com/wikimedia/mediawiki/blob/6abd0c0c3b6f8a8f7eab7d4b93c47216e1827a05/includes/libs/rdbms/database/DatabaseMysqlBase.php#L952 , whatever might be causing that is what's causing the failure in LBFactory.php to throw a DBReplicationWaitError.

**Comment by addshore** [comment]
@cdrini Also going to close this one as it has been inactive for some time.
If it is still happening though feel free to poke this back!
