### ISSUE TITLE
Unable to access sites

### ISSUE THREAD

**Issue by cdrini** [addshore/mediawiki-docker-dev#68]
I can't seem to access anything. I thought it might be because of #67 , but I still can't access anything after switching to the masterOnly branch.

I'm running Windows 10 with Docker Toolbox.

Note that since I'm using Docker Toolbox, I use port 192.168.99.100 instead of 127.0.0.1.
192.168.99.100:8080 gives me "503 Service Temporarily Unavailable" from nginx/1.14.0
http://default.web.mw.localhost:8080/ (and all others) give a chrome "refused to connect" error

Here's what's in my hosts file at ` /c/Windows/System32/Drivers/etc/hosts`:
```
192.168.99.100  default.web.mw.localhost
192.168.99.100  proxy.mw.localhost
192.168.99.100  phpmyadmin.mw.localhost
192.168.99.100  graphite.mw.localhost
```

The hosts file is working; I can `ping`  default.web.mw.localhost and it resolves correctly.

Are there any other settings I need to modify to get things working with 192.168.99.100 ? Is this what's causing the issue in the first place, or is it something else?

**Comment by addshore** [comment]
Hmmmmmmmmm.
Without looking into it too much I feel like it could be a chrome issue? perhaps?
What happens if you use curl to request the wiki @ default.web.mw.localhost ?
What is the response?

**Comment by addshore** [comment]
@cdrini did you ever manage to fix this?
Going to close this as it has been inactive for some time, but feel free to come back if you need to!
