### ISSUE TITLE
Only start what's needed

### ISSUE THREAD

**Issue by gbirke** [addshore/mediawiki-docker-dev#7]
I like the "everything and the kitchen sink" approach of the script, but I guess it's heavily tailored to your use case, right? I don't use Graphite and PHPMyAdmin that much and could do without HHVM, multiple web servers and multiple DBs. And the options will multiply when this supports more features (think of the roles of the Vagrant image).

I'd like to work on some configurability and have two possibilities in mind:
a) A generator for `Dockerfile` and `docker-compose.yml`, like on https://phpdocker.io/generator
b) A service-discovery and DNS service like [Consul](https://www.consul.io) with some modifications to docker-compose where only a basic MW environment is started (you could always define what _you_ consider basic in an [override file](https://docs.docker.com/compose/extends/#understanding-multiple-compose-files). The setup scripts would have to be modularized to do the setup only for a given container.

The generator solution is more easy to implement but will mean that everyone will have their own version of the environment. So I guess I might have a look at the modularization thing ...

Ideas and feedback welcome.

**Comment by addshore** [comment]
So, I have already started a push in this direction before you filed this ticket, and here is my initial effort.

https://github.com/addshore/mediawiki-docker-dev/commit/54a4001991ff1ead65504b5a019ab0624e1b66a2

This essentially only creates 1 web container and 1 db container and these are configured based on the local.env environment variables file that overrides the default.env

We could probably also add switches for things like PHPMYADMIN and STATSD/GRAPHITE in the same way.

**Comment by addshore** [comment]
So, I could rewrite the up command and the general workflow and probably make this work.
Would probably have to use etcd for mediawiki confing, OR just make the localsettings we load look in a dir and load ann php snippets / files in there.

I'm planning on looking into kubernetes for this dev environment, so will see if it can be done at the same time.
I'd like to expand the services this thing has.

**Comment by gbirke** [comment]
Just a side note - probably every developer needs a different environment. For example, I've added Elasticsearch while I was working on the AdvancedSearch extension: https://github.com/gbirke/mediawiki-docker-dev/commit/4efa6bc1bf4d6bfb02d7cd3a25477e326814f69c

I don't know what a good configuration mechanism would be. For new developers probably a yes/no config where they can activate/deactivate services. The necessary background configuration (configuring the service to work inside the container, bootstrapping the service with initial data, adding PHP config entries to MediaWiki config, configure the container network to use/expose the right ports/subdomains) should work with that yes/no config.

More experienced devs might override individual service configuration and/or  MediaWiki config PHP entries.

**Comment by addshore** [comment]
This is implemented in https://www.mediawiki.org/wiki/Cli
