### ISSUE TITLE
Best practices for managing additional services

### ISSUE THREAD

**Issue by kostajh** [addshore/mediawiki-docker-dev#71]
Curious if there is a recommendation for best practices in managing additional services.

#70 is one example, but a simpler one is something like adding Redis for JobQueue. To `docker-compose.yml` one can add

``` yaml
redis:
  image: redis
```

And then in `LocalSettings.php` you can have

``` php
$wgObjectCaches['redis'] = array(
	'class'                => 'RedisBagOStuff',
	'servers'              => array( 'redis:6379' ),
);
$wgJobTypeConf['default'] = [
	'class'          => 'JobQueueRedis',
	'redisServer'    => 'redis:6379',
	'redisConfig'    => [],
	'claimTTL'       => 3600,
	'daemonized'     => true
];
```

Which is easy enough to add/remove, but one advantage of `mw-vagrant` is that you can enable / disable these types of configurations, and it's a more manual process with this project.

**Comment by addshore** [comment]
So, the biggest question to figure out how to make this work is what do we want the UX to be for us developers?

 - Define the services to be created when running "up" in the env file? This might require running down and up again before adding new services?
 - Have "up" create a baseline and then have subsequent "up" commands add to that, for example "up phpmyadmin" or "up redis".
 - Do we want to restructure how the commands work / what commands we have? Maybe one main command with sub commands etc.
 - How plug and play do we want this to be? Do we want other people to be able to add their own docker-compose snippets? Is it okay for everything to be contained in this repo?

I might start having an experiment on a branch

**Comment by kostajh** [comment]
Sorry for the delayed response. I can write more later but just wanted to say, perhaps we should see what comes [of this position](https://boards.greenhouse.io/wikimedia/jobs/1225258?gh_src=f15731e11) before we sink a bunch of time into figuring out the somewhat difficult questions listed above.

**Comment by kostajh** [comment]
One idea would be to have a page on mediawiki.org where we can at least start collecting how-to guides for seting up various services, that people can then copy/paste into their LocalSettings + docker-compose.yml files. It's not sustainable in the long term but we could at least get knowledge out to people in the short term.

**Comment by kostajh** [comment]
I created a page and started documenting how I've wired together different services. https://www.mediawiki.org/wiki/MediaWiki-Docker-Dev

**Comment by addshore** [comment]
I want to try and work on this a bit over the coming weeks and for example make the graphite / statsd service optional.
Probably then loading the config in LS.php using a check with gethostbyname to see if the service is registered or not.

**Comment by kostajh** [comment]
One way to do this would be to use [multiple compose files](https://docs.docker.com/compose/extends/). We can take advantage of the fact that we have a `local.env` file to manage the state of which additional services are loaded.

So, for example we could add a `services` directory with `docker-compose.{service-name}.yml`, e.g. `services/docker-compose.redis.yml`, and further more its default PHP configuration as `{service-name}.config.php`, e.g. `redis.config.php`.

At the top of our LocalSettings.php file where we load `.docker/LocalSettings.php`, we could add an additional snippet of code to require all PHP files in `.docker/services/*.php`.

We could have a bash script like `./service {enable|disable} {service-name}` and use that to add/remove the entry from `local.env`, then when using `./up` we can chain the relevant services files as needed.

**Comment by addshore** [comment]
Some of my related thoughts are in #84 and https://github.com/addshore/mediawiki-docker-dev/pull/82#issuecomment-465059407

**Comment by addshore** [comment]
https://phabricator.wikimedia.org/T282356 for mwcli
