### ISSUE TITLE
Naming things is hard

### ISSUE THREAD

**Issue by Krinkle** [addshore/mediawiki-docker-dev#80]
Currently, the names for the subset of scripts that change the existence or state of the environment, are:

* `mdd up`
* `mdd down`
* `mdd stop`
* `mdd start`

And soon:
* `mdd setup` – https://github.com/addshore/mediawiki-docker-dev/pull/76

Proposal:

* `mdd install`
* `mdd create`
* `mdd destroy`
* `mdd suspend`
* `mdd resume`

**Comment by kostajh** [comment]
I have inadvertently destroyed my database with “down” before; “destroy” and “suspend” would be more clear IMO.

**Comment by addshore** [comment]
Sounds like a great naming change.
