### ISSUE TITLE
mwdd-cli, a single command / script for all of the things?

### ISSUE THREAD

**Issue by addshore** [addshore/mediawiki-docker-dev#84]
I think a nice goal here might be to write a nice CLI (single script) to manage all part of the dev env.
For example you could do.

mwdd start
mwdd addsite secondsite
mwdd addservice redis # Add as redis server (and perhaps auto connect it to mw?)
mwdd stop
mwdd setserviceversion web php7.1
mwdd setserviceversion web php7.2 # throw away the current web instance, and load up the 7.2 flavour
mwdd shell web # load into a shell in the web service

Each command could manipulate a controlled docker-compose file, or manipulate a series of docker-compose extension files.

The CLID script could even be in its own docker image / run from a container?
If it runs in its own container, we could easily use a nice language to write this in and not require people to install anything extra.

**Comment by Krinkle** [comment]
> The CLID script could even be in its own docker image / run from a container?
>
> If it runs in its own container, we could easily use a nice language to write this in and not require people to install anything extra.

Given that this will need a lot of system access, I'd prefer it be something portable, simple, and reasonably ubiquitous, e.g. Python 3.5+. This is pre-installed on macOS and most Linux distros.

That way users don't have to download and trust more large binaries. We could, however, have a documented shortcut for running it via a Docker container for anyone that wants to.

E.g.

```
docker run -it --rm --name mdd-cli -v "$PWD":/usr/src/mdd -w /usr/src/mdd \
  python:3 \
  python3 bin/mdd
```

**Comment by kostajh** [comment]
A single entrypoint would be nice. I've used a Makefile in the past, and that works reasonably well for completion of commands, and also showing available commands.

For more complexity, we could probably learn from https://github.com/lando/lando and https://github.com/drud/ddev among others.

**Comment by addshore** [comment]
https://github.com/lando/lando looks great

**Comment by addshore** [comment]
https://www.mediawiki.org/wiki/Cli
