### ISSUE TITLE
add wikidiff2

### ISSUE THREAD

**Issue by micgro42** [addshore/mediawiki-docker-dev#85]
Hi,

the last days I spend a lot of time working out why a diff-test succeeded locally, but failed on CI. It turns out that there are multiple engines to compute the diff. The default way, which this docker env is currently limited to, is to use the DiffEngine written in PHP. 
However, CI uses [wikidiff2](https://www.mediawiki.org/wiki/Extension:Wikidiff2). Wikidiff2 is not an actual MediaWiki extension, but an OS binary and hence it might be sensible if this docker container setup would provide it too.

**Comment by addshore** [comment]
In order to cater for cases like this really we need to have our own docker images with these extra things added, OR use the base mediawiki image which has some of them (but also not the flexibility of switching php version etc.

Thoughts?

I also recently had a similar issue where i wanted to install lilypond to work with the Score extension.

**Comment by Krinkle** [comment]
@addshore Perhaps that could be one of the `web` flavours?

E.g. in addition to values that map to the webdevops images (with Ubuntu versions, Debian versions, PHP versions, Apache or Nginx), there could also be special value like "dockerhub-mediawiki" or some such, that would the more wmf-like (but inflexible) image instead.

Supporting both in this way I think would be useful and possible, but not without added cost. It probably needs different environment variables and mounts that we'll need to find a way to make dynamic, or to give it a different name (e.g. "plain" and "wmf"), with different hostnames. Then, to optimise for speed we'd need a way to toggle on/off parts of docker-compose.

Different question - is there currently a "mediawiki base image" available on Dockerhub that doesn't have its own database, and allows mounting a custom MediaWiki installation?

* <https://hub.docker.com/_/mediawiki/>: Doesn't promote mounting of MW installs, but does promote DB config.
* <https://github.com/wikimedia/mediawiki-docker>: Has a "dev" folder, which, if I understand correctly, goes to <https://hub.docker.com/r/wikimedia/mediawiki/> instead, which tracks WMF branches. If that allows easy mounting, maybe that's what we should use? See also <https://github.com/wikimedia/mediawiki-docker/pull/45>.

@addshore Which image did you have in mind?

**Comment by addshore** [comment]
Thats a great idea.

* https://hub.docker.com/_/mediawiki/: Doesn't promote mounting of MW installs, but does promote DB config can be made to work.

I think perhaps before layering up some more complexity it might be worth looking at https://github.com/addshore/mediawiki-docker-dev/issues/84

**Comment by micgro42** [comment]
Just as a note here, it would be nice if we could also add `php-ast` to the things provided by the image. It is needed to use the [`phan` static analyzer][0], which is [available on CI][1]. Should I update the original post for this?

[0]: https://www.mediawiki.org/wiki/Continuous_integration/Tutorials/Add_phan_to_a_MediaWiki_extension
[1]: https://lists.wikimedia.org/pipermail/wikitech-l/2019-February/091586.html

**Comment by addshore** [comment]
> Just as a note here, it would be nice if we could also add `php-ast` to the things provided by the image. It is needed to use the [`phan` static analyzer](https://www.mediawiki.org/wiki/Continuous_integration/Tutorials/Add_phan_to_a_MediaWiki_extension), which is [available on CI](https://lists.wikimedia.org/pipermail/wikitech-l/2019-February/091586.html). Should I update the original post for this?

ast probably shouldn't be included in this image, as it is not needed for mediawiki or extensions to run.
It would make sense to try and pull the quibble images that run in CI into this setup, so that they could easily be used to run any needed tests etc.

**Comment by addshore** [comment]
Moving to https://phabricator.wikimedia.org/T294183 for mwcli
