### ISSUE TITLE
How to customize PHP image settings?

### ISSUE THREAD

**Issue by egardner** [addshore/mediawiki-docker-dev#86]
I'm new to both Mediawiki and Docker – as well as PHP generally – so apologies for asking a question that may be obvious.

After initial setup of my environment using the `create` script, I attempted to import a category of Wikipedia pages & templates in order to have some sample content to work with. I'm using the Special:Import page as opposed to just importing a SQL dump directly.

Unfortunately, the upload limit in the PHP container seems to be very low by default. Even a 1MB file still returns a `413 Request Entity Too Large` error.

My question is – is there a straightforward way to tweak some PHP settings without having to use a different image entirely? Maybe this could be done in `docker-compose.override.yml` somehow?

I ended up [building my own](https://gist.github.com/egardner/b4e16a9360c39d7c17a5eb44dd915a7d) (very minimal) setup around the [mediawiki-docker](https://github.com/wikimedia/mediawiki-docker/blob/master/1.32/Dockerfile) image instead, where I was able to create a custom `uploads.ini` file and then add a line to `COPY` it when the mediawiki-docker image starts up. 

I would prefer to use this repo to take advantage of all the other work that has been done already – any suggestions on how to make this kind of customization would be very helpful. Thanks!

**Comment by addshore** [comment]
Per https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-apache-dev.html the env var PHP_UPLOAD_MAX_FILESIZE can be used to set the max filesize.
Maybe we should set a larger default for the mwdd setup.
Current default is 50M

**Comment by addshore** [comment]
> Even a 1MB file still returns a `413 Request Entity Too Large` error

Interesting, are you getting the 413 from apache / the webserver serving mediawiki or from the nginx image in front of it that is routing to the various places?

**Comment by addshore** [comment]
Looks like it is probably the nginx container https://github.com/jwilder/nginx-proxy/issues/981

**Comment by egardner** [comment]
I was getting an nginx error, yes. Thanks for finding that issue, I'll take a look. It may be worth adding something to the README about modifying these settings, as I imagine that uploading a large XML file into Special:Import is a common use-case.

**Comment by addshore** [comment]
Feel free to make a PR :)
