### ISSUE TITLE
Use with ngrok or local network

### ISSUE THREAD

**Issue by kostajh** [addshore/mediawiki-docker-dev#90]
I'd like to be able to share my environment to the outside world, whether it's with ngrok (`ngrok http default.web.mw.localhost`) or by plugging in my phone to my computer and navigating to my computer's network name.

Neither of these work. With ngrok, I get `503 Service Temporarily Unavailable`.

With the local network approach (I'm on macOS, and in System Preferences -> Sharing I have my computer name for local network requests defined as `kafes.local`), my custom network name doesn't correspond to the expected domain of `default.web.mw.localhost`. I made some progress by renaming the web container to `kafes.local` and updating hardcoded references to `web.mw.localhost` with `kafes.local` but while the initial request to the domain worked, subsequent requests to load.php failed. Also, this isn't really sustainable.

My main motivation for needing this is so I can plug in my phone and test mobile code on a real device, with a debugger attached to it.

Any ideas?

**Comment by addshore** [comment]
Tracked for mwcli as https://phabricator.wikimedia.org/T292897
