### ISSUE TITLE
provide scripts to easily backup and restore a DB?

### ISSUE THREAD

**Issue by addshore** [addshore/mediawiki-docker-dev#91]

**Comment by micgro42** [comment]
Either an entire db (not sure how useful that would be) or just some pages or namespaces. E.g. to create some bootstrapping beyond the default

**Comment by Krinkle** [comment]
The main use case I have is to be able to switch operational variables (e.g. php version) and thus do a destroy-create cycle without losing the database and image uploads along with it.

The destroy-create cycle is super fast, so I don't mind doing that often (which is also why I don't think we need to support multiple php versions concurrently). But having to re-create certain test pages, interface messages, user accounts, user preferences etc is a hassle I'd like to avoid.

If that's the same use case as @addshore has, then we might be able to solve it in a different way instead (without needing to backup/restore the db explicitly). Is it possible to tell docker-composer to destroy only part of the composition and then have it create only what's missing/changed?

**Comment by addshore** [comment]
Declining for now
Happy to have this reopened against mwcli perhaps
