### ISSUE TITLE
Additional VSCode debugging info to README 

### ISSUE THREAD

**Issue by nikkhn** [addshore/mediawiki-docker-dev#98]
I ran into a few issues when debugging (in Visual Studio Code), and wanted to throw in a few more notes into the Debugging section of the README that might be helpful to future devs. Alright if I put in a PR out for the addition ?

**Comment by Krinkle** [comment]
Yes, absolutely!

**Comment by nikkhn** [comment]
Great thanks!

**Comment by addshore** [comment]
I guess this was done in:

https://github.com/addshore/mediawiki-docker-dev/commit/bf7873415a8b84633d5970caf1fca4ceaf4659c9
https://github.com/addshore/mediawiki-docker-dev/commit/c36d0ab448fff48de0807b24d7e7f1bad0cb7b8c
https://github.com/addshore/mediawiki-docker-dev/commit/1de91f958c889ef3f74b77c00c28a2f6f91cf384 

?

Please re open if not :)
